AWSTemplateFormatVersion: '2010-09-09'
Description: Doctor CRUD using Lambda + API Gateway + S3 JSON (no SAM)

Parameters:
  BucketName:
    Type: String
    Default: s3-jsvm-dev-doctor-service-db

Resources:

  ### ---------------- S3 BUCKET ----------------
  DoctorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  ### ---------------- IAM ROLE ----------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: lambda-logs-s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

  ### ---------------- LAMBDAS ----------------
  CreateDoctorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CreateDoctorFunction
      Runtime: python3.11
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Code:
        S3Bucket: s3-jsvm-services
        S3Key: dev-doctor-service/createDoctor.zip
      Layers:
        - !Ref CommonLayer

  GetDoctorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GetDoctorFunction
      Runtime: python3.11
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Code:
        S3Bucket: s3-jsvm-services
        S3Key: dev-doctor-service/getDoctor.zip
      Layers:
        - !Ref CommonLayer

  GetAllDoctorsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GetAllDoctorsFunction
      Runtime: python3.11
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Code:
        S3Bucket: s3-jsvm-services
        S3Key: dev-doctor-service/getAllDoctors.zip
      Layers:
        - !Ref CommonLayer

  UpdateDoctorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UpdateDoctorFunction
      Runtime: python3.11
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Code:
        S3Bucket: s3-jsvm-services
        S3Key: dev-doctor-service/updateDoctor.zip
      Layers:
        - !Ref CommonLayer

  DeleteDoctorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DeleteDoctorFunction
      Runtime: python3.11
      Handler: handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Code:
        S3Bucket: s3-jsvm-services
        S3Key: dev-doctor-service/deleteDoctor.zip
      Layers:
        - !Ref CommonLayer
  ### ---------------- API ----------------

  DoctorApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: DoctorApi

  DoctorResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt DoctorApi.RootResourceId
      PathPart: doctors
      RestApiId: !Ref DoctorApi

  DoctorIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref DoctorResource
      PathPart: "{id}"
      RestApiId: !Ref DoctorApi

  ### ---------------- METHODS ----------------

  CreateDoctorMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DoctorApi
      ResourceId: !Ref DoctorResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateDoctorFunction.Arn}/invocations

  GetDoctorMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DoctorApi
      ResourceId: !Ref DoctorIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDoctorFunction.Arn}/invocations

  GetAllDoctorsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DoctorApi
      ResourceId: !Ref DoctorResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAllDoctorsFunction.Arn}/invocations

  UpdateDoctorMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DoctorApi
      ResourceId: !Ref DoctorIdResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateDoctorFunction.Arn}/invocations

  DeleteDoctorMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref DoctorApi
      ResourceId: !Ref DoctorIdResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteDoctorFunction.Arn}/invocations

  ### ---------------- PERMISSIONS ----------------

  LambdaInvokePermissionCreate:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateDoctorFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DoctorApi}/*

  LambdaInvokePermissionGet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetDoctorFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DoctorApi}/*

  LambdaInvokePermissionGetAll:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetAllDoctorsFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DoctorApi}/*

  LambdaInvokePermissionUpdate:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateDoctorFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DoctorApi}/*

  LambdaInvokePermissionDelete:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteDoctorFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DoctorApi}/*

  ### ---------------- DEPLOY ----------------

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CreateDoctorMethod
      - GetDoctorMethod
      - GetAllDoctorsMethod
      - UpdateDoctorMethod
      - DeleteDoctorMethod
    Properties:
      RestApiId: !Ref DoctorApi
      StageName: prod

  CommonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: common-layer
      Description: Shared utilities for Lambdas
      Content:
        S3Bucket: s3-jsvm-services
        S3Key: dev-doctor-service/common-layer.zip
      CompatibleRuntimes:
        - python3.11
Outputs:
  ApiUrl:
    Value: !Sub "https://${DoctorApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"