AWSTemplateFormatVersion: '2010-09-09'
Description: Base Infra (S3 Artifacts Bucket)

Parameters:
  Environment:
    Type: String

Resources:

  CodeArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-jsvm-code-artifacts"

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Value: !Ref CodeArtifactsBucket