AWSTemplateFormatVersion: '2010-09-09'
Description: Bootstrap Platform Infra (SSM + Code Bucket)

Parameters:
  Environment:
    Type: String

Resources:

  ########################################
  # CODE ARTIFACT BUCKET
  ########################################
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jsvm-code-artifacts
      VersioningConfiguration:
        Status: Enabled

  ########################################
  # SSM - SOURCE OF TRUTH
  ########################################
  CodeBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/jsvm/${Environment}/code-bucket"
      Type: String
      Value: !Ref CodeBucket

  EnvParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/jsvm/${Environment}/env"
      Type: String
      Value: !Ref Environment

Outputs:
  BucketName:
    Value: !Ref CodeBucket