AWSTemplateFormatVersion: '2010-09-09'
Description: Bootstrap Platform Infra (SSM + Code Bucket)

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]

Resources:

  ########################################
  # CODE ARTIFACT BUCKET
  ########################################
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jsvm-code-artifacts
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref CodeBucket